package net.minestom.server.instance.block;

/**
 * This class contains all the generated constants for {@link BlockProperty}
 * <br>
 * Code autogenerated, do not edit!
 */
sealed interface BlockProperties permits BlockProperty {
    BlockProperty.Integer AGE_1 = new BlockPropertyImpl.IntImpl("age", 0, 1);

    BlockProperty.Integer AGE_15 = new BlockPropertyImpl.IntImpl("age", 0, 15);

    BlockProperty.Integer AGE_2 = new BlockPropertyImpl.IntImpl("age", 0, 2);

    BlockProperty.Integer AGE_25 = new BlockPropertyImpl.IntImpl("age", 0, 25);

    BlockProperty.Integer AGE_3 = new BlockPropertyImpl.IntImpl("age", 0, 3);

    BlockProperty.Integer AGE_4 = new BlockPropertyImpl.IntImpl("age", 0, 4);

    BlockProperty.Integer AGE_5 = new BlockPropertyImpl.IntImpl("age", 0, 5);

    BlockProperty.Integer AGE_7 = new BlockPropertyImpl.IntImpl("age", 0, 7);

    BlockProperty.Boolean ATTACHED = new BlockPropertyImpl.BooleanImpl("attached");

    BlockProperty.Enum<AttachFace> ATTACH_FACE = new BlockPropertyImpl.EnumImpl<>("face", AttachFace.class);

    BlockProperty.Enum<Axis> AXIS = new BlockPropertyImpl.EnumImpl<>("axis", Axis.class);

    BlockProperty.Enum<BambooLeaves> BAMBOO_LEAVES = new BlockPropertyImpl.EnumImpl<>("leaves", BambooLeaves.class);

    BlockProperty.Enum<BedPart> BED_PART = new BlockPropertyImpl.EnumImpl<>("part", BedPart.class);

    BlockProperty.Enum<BellAttachType> BELL_ATTACHMENT = new BlockPropertyImpl.EnumImpl<>("attachment", BellAttachType.class);

    BlockProperty.Boolean BERRIES = new BlockPropertyImpl.BooleanImpl("berries");

    BlockProperty.Integer BITES = new BlockPropertyImpl.IntImpl("bites", 0, 6);

    BlockProperty.Boolean BLOOM = new BlockPropertyImpl.BooleanImpl("bloom");

    BlockProperty.Boolean BOTTOM = new BlockPropertyImpl.BooleanImpl("bottom");

    BlockProperty.Integer CANDLES = new BlockPropertyImpl.IntImpl("candles", 1, 4);

    BlockProperty.Boolean CAN_SUMMON = new BlockPropertyImpl.BooleanImpl("can_summon");

    BlockProperty.Enum<ChestType> CHEST_TYPE = new BlockPropertyImpl.EnumImpl<>("type", ChestType.class);

    BlockProperty.Boolean CONDITIONAL = new BlockPropertyImpl.BooleanImpl("conditional");

    BlockProperty.Enum<Pose> COPPER_GOLEM_POSE = new BlockPropertyImpl.EnumImpl<>("copper_golem_pose", Pose.class);

    BlockProperty.Boolean CRACKED = new BlockPropertyImpl.BooleanImpl("cracked");

    BlockProperty.Boolean CRAFTING = new BlockPropertyImpl.BooleanImpl("crafting");

    BlockProperty.Enum<CreakingHeartState> CREAKING_HEART_STATE = new BlockPropertyImpl.EnumImpl<>("creaking_heart_state", CreakingHeartState.class);

    BlockProperty.Integer DELAY = new BlockPropertyImpl.IntImpl("delay", 1, 4);

    BlockProperty.Boolean DISARMED = new BlockPropertyImpl.BooleanImpl("disarmed");

    BlockProperty.Integer DISTANCE = new BlockPropertyImpl.IntImpl("distance", 1, 7);

    BlockProperty.Enum<DoorHingeSide> DOOR_HINGE = new BlockPropertyImpl.EnumImpl<>("hinge", DoorHingeSide.class);

    BlockProperty.Enum<DoubleBlockHalf> DOUBLE_BLOCK_HALF = new BlockPropertyImpl.EnumImpl<>("half", DoubleBlockHalf.class);

    BlockProperty.Boolean DOWN = new BlockPropertyImpl.BooleanImpl("down");

    BlockProperty.Boolean DRAG = new BlockPropertyImpl.BooleanImpl("drag");

    BlockProperty.Integer DRIED_GHAST_HYDRATION_LEVELS = new BlockPropertyImpl.IntImpl("hydration", 0, 3);

    BlockProperty.Enum<DripstoneThickness> DRIPSTONE_THICKNESS = new BlockPropertyImpl.EnumImpl<>("thickness", DripstoneThickness.class);

    BlockProperty.Integer DUSTED = new BlockPropertyImpl.IntImpl("dusted", 0, 3);

    BlockProperty.Boolean EAST = new BlockPropertyImpl.BooleanImpl("east");

    BlockProperty.Enum<RedstoneSide> EAST_REDSTONE = new BlockPropertyImpl.EnumImpl<>("east", RedstoneSide.class);

    BlockProperty.Enum<WallSide> EAST_WALL = new BlockPropertyImpl.EnumImpl<>("east", WallSide.class);

    BlockProperty.Integer EGGS = new BlockPropertyImpl.IntImpl("eggs", 1, 4);

    BlockProperty.Boolean ENABLED = new BlockPropertyImpl.BooleanImpl("enabled");

    BlockProperty.Boolean EXTENDED = new BlockPropertyImpl.BooleanImpl("extended");

    BlockProperty.Boolean EYE = new BlockPropertyImpl.BooleanImpl("eye");

    BlockProperty.Enum<Direction> FACING = new BlockPropertyImpl.EnumImpl<>("facing", Direction.class);

    BlockProperty.Enum<Direction> FACING_HOPPER = new BlockPropertyImpl.EnumImpl<>("facing", Direction.class);

    BlockProperty.Boolean FALLING = new BlockPropertyImpl.BooleanImpl("falling");

    BlockProperty.Integer FLOWER_AMOUNT = new BlockPropertyImpl.IntImpl("flower_amount", 1, 4);

    BlockProperty.Enum<Half> HALF = new BlockPropertyImpl.EnumImpl<>("half", Half.class);

    BlockProperty.Boolean HANGING = new BlockPropertyImpl.BooleanImpl("hanging");

    BlockProperty.Boolean HAS_BOOK = new BlockPropertyImpl.BooleanImpl("has_book");

    BlockProperty.Boolean HAS_BOTTLE_0 = new BlockPropertyImpl.BooleanImpl("has_bottle_0");

    BlockProperty.Boolean HAS_BOTTLE_1 = new BlockPropertyImpl.BooleanImpl("has_bottle_1");

    BlockProperty.Boolean HAS_BOTTLE_2 = new BlockPropertyImpl.BooleanImpl("has_bottle_2");

    BlockProperty.Boolean HAS_RECORD = new BlockPropertyImpl.BooleanImpl("has_record");

    BlockProperty.Integer HATCH = new BlockPropertyImpl.IntImpl("hatch", 0, 2);

    BlockProperty.Enum<Axis> HORIZONTAL_AXIS = new BlockPropertyImpl.EnumImpl<>("axis", Axis.class);

    BlockProperty.Enum<Direction> HORIZONTAL_FACING = new BlockPropertyImpl.EnumImpl<>("facing", Direction.class);

    BlockProperty.Boolean INVERTED = new BlockPropertyImpl.BooleanImpl("inverted");

    BlockProperty.Boolean IN_WALL = new BlockPropertyImpl.BooleanImpl("in_wall");

    BlockProperty.Integer LAYERS = new BlockPropertyImpl.IntImpl("layers", 1, 8);

    BlockProperty.Integer LEVEL = new BlockPropertyImpl.IntImpl("level", 0, 15);

    BlockProperty.Integer LEVEL_CAULDRON = new BlockPropertyImpl.IntImpl("level", 1, 3);

    BlockProperty.Integer LEVEL_COMPOSTER = new BlockPropertyImpl.IntImpl("level", 0, 8);

    BlockProperty.Integer LEVEL_FLOWING = new BlockPropertyImpl.IntImpl("level", 1, 8);

    BlockProperty.Integer LEVEL_HONEY = new BlockPropertyImpl.IntImpl("honey_level", 0, 5);

    BlockProperty.Boolean LIT = new BlockPropertyImpl.BooleanImpl("lit");

    BlockProperty.Boolean LOCKED = new BlockPropertyImpl.BooleanImpl("locked");

    BlockProperty.Boolean MAP = new BlockPropertyImpl.BooleanImpl("map");

    BlockProperty.Enum<ComparatorMode> MODE_COMPARATOR = new BlockPropertyImpl.EnumImpl<>("mode", ComparatorMode.class);

    BlockProperty.Integer MOISTURE = new BlockPropertyImpl.IntImpl("moisture", 0, 7);

    BlockProperty.Boolean NATURAL = new BlockPropertyImpl.BooleanImpl("natural");

    BlockProperty.Boolean NORTH = new BlockPropertyImpl.BooleanImpl("north");

    BlockProperty.Enum<RedstoneSide> NORTH_REDSTONE = new BlockPropertyImpl.EnumImpl<>("north", RedstoneSide.class);

    BlockProperty.Enum<WallSide> NORTH_WALL = new BlockPropertyImpl.EnumImpl<>("north", WallSide.class);

    BlockProperty.Integer NOTE = new BlockPropertyImpl.IntImpl("note", 0, 24);

    BlockProperty.Enum<NoteBlockInstrument> NOTEBLOCK_INSTRUMENT = new BlockPropertyImpl.EnumImpl<>("instrument", NoteBlockInstrument.class);

    BlockProperty.Boolean OCCUPIED = new BlockPropertyImpl.BooleanImpl("occupied");

    BlockProperty.Boolean OMINOUS = new BlockPropertyImpl.BooleanImpl("ominous");

    BlockProperty.Boolean OPEN = new BlockPropertyImpl.BooleanImpl("open");

    BlockProperty.Enum<FrontAndTop> ORIENTATION = new BlockPropertyImpl.EnumImpl<>("orientation", FrontAndTop.class);

    BlockProperty.Boolean PERSISTENT = new BlockPropertyImpl.BooleanImpl("persistent");

    BlockProperty.Integer PICKLES = new BlockPropertyImpl.IntImpl("pickles", 1, 4);

    BlockProperty.Enum<PistonType> PISTON_TYPE = new BlockPropertyImpl.EnumImpl<>("type", PistonType.class);

    BlockProperty.Integer POWER = new BlockPropertyImpl.IntImpl("power", 0, 15);

    BlockProperty.Boolean POWERED = new BlockPropertyImpl.BooleanImpl("powered");

    BlockProperty.Enum<RailShape> RAIL_SHAPE = new BlockPropertyImpl.EnumImpl<>("shape", RailShape.class);

    BlockProperty.Enum<RailShape> RAIL_SHAPE_STRAIGHT = new BlockPropertyImpl.EnumImpl<>("shape", RailShape.class);

    BlockProperty.Integer RESPAWN_ANCHOR_CHARGES = new BlockPropertyImpl.IntImpl("charges", 0, 4);

    BlockProperty.Integer ROTATION_16 = new BlockPropertyImpl.IntImpl("rotation", 0, 15);

    BlockProperty.Enum<SculkSensorPhase> SCULK_SENSOR_PHASE = new BlockPropertyImpl.EnumImpl<>("sculk_sensor_phase", SculkSensorPhase.class);

    BlockProperty.Integer SEGMENT_AMOUNT = new BlockPropertyImpl.IntImpl("segment_amount", 1, 4);

    BlockProperty.Boolean SHORT = new BlockPropertyImpl.BooleanImpl("short");

    BlockProperty.Boolean SHRIEKING = new BlockPropertyImpl.BooleanImpl("shrieking");

    BlockProperty.Enum<SideChainPart> SIDE_CHAIN_PART = new BlockPropertyImpl.EnumImpl<>("side_chain", SideChainPart.class);

    BlockProperty.Boolean SIGNAL_FIRE = new BlockPropertyImpl.BooleanImpl("signal_fire");

    BlockProperty.Enum<SlabType> SLAB_TYPE = new BlockPropertyImpl.EnumImpl<>("type", SlabType.class);

    BlockProperty.Boolean SLOT_0_OCCUPIED = new BlockPropertyImpl.BooleanImpl("slot_0_occupied");

    BlockProperty.Boolean SLOT_1_OCCUPIED = new BlockPropertyImpl.BooleanImpl("slot_1_occupied");

    BlockProperty.Boolean SLOT_2_OCCUPIED = new BlockPropertyImpl.BooleanImpl("slot_2_occupied");

    BlockProperty.Boolean SLOT_3_OCCUPIED = new BlockPropertyImpl.BooleanImpl("slot_3_occupied");

    BlockProperty.Boolean SLOT_4_OCCUPIED = new BlockPropertyImpl.BooleanImpl("slot_4_occupied");

    BlockProperty.Boolean SLOT_5_OCCUPIED = new BlockPropertyImpl.BooleanImpl("slot_5_occupied");

    BlockProperty.Boolean SNOWY = new BlockPropertyImpl.BooleanImpl("snowy");

    BlockProperty.Boolean SOUTH = new BlockPropertyImpl.BooleanImpl("south");

    BlockProperty.Enum<RedstoneSide> SOUTH_REDSTONE = new BlockPropertyImpl.EnumImpl<>("south", RedstoneSide.class);

    BlockProperty.Enum<WallSide> SOUTH_WALL = new BlockPropertyImpl.EnumImpl<>("south", WallSide.class);

    BlockProperty.Integer STABILITY_DISTANCE = new BlockPropertyImpl.IntImpl("distance", 0, 7);

    BlockProperty.Integer STAGE = new BlockPropertyImpl.IntImpl("stage", 0, 1);

    BlockProperty.Enum<StairsShape> STAIRS_SHAPE = new BlockPropertyImpl.EnumImpl<>("shape", StairsShape.class);

    BlockProperty.Enum<StructureMode> STRUCTUREBLOCK_MODE = new BlockPropertyImpl.EnumImpl<>("mode", StructureMode.class);

    BlockProperty.Enum<TestBlockMode> TEST_BLOCK_MODE = new BlockPropertyImpl.EnumImpl<>("mode", TestBlockMode.class);

    BlockProperty.Enum<Tilt> TILT = new BlockPropertyImpl.EnumImpl<>("tilt", Tilt.class);

    BlockProperty.Boolean TIP = new BlockPropertyImpl.BooleanImpl("tip");

    BlockProperty.Enum<TrialSpawnerState> TRIAL_SPAWNER_STATE = new BlockPropertyImpl.EnumImpl<>("trial_spawner_state", TrialSpawnerState.class);

    BlockProperty.Boolean TRIGGERED = new BlockPropertyImpl.BooleanImpl("triggered");

    BlockProperty.Boolean UNSTABLE = new BlockPropertyImpl.BooleanImpl("unstable");

    BlockProperty.Boolean UP = new BlockPropertyImpl.BooleanImpl("up");

    BlockProperty.Enum<VaultState> VAULT_STATE = new BlockPropertyImpl.EnumImpl<>("vault_state", VaultState.class);

    BlockProperty.Enum<Direction> VERTICAL_DIRECTION = new BlockPropertyImpl.EnumImpl<>("vertical_direction", Direction.class);

    BlockProperty.Boolean WATERLOGGED = new BlockPropertyImpl.BooleanImpl("waterlogged");

    BlockProperty.Boolean WEST = new BlockPropertyImpl.BooleanImpl("west");

    BlockProperty.Enum<RedstoneSide> WEST_REDSTONE = new BlockPropertyImpl.EnumImpl<>("west", RedstoneSide.class);

    BlockProperty.Enum<WallSide> WEST_WALL = new BlockPropertyImpl.EnumImpl<>("west", WallSide.class);

    enum AttachFace {
        FLOOR("floor"),

        WALL("wall"),

        CEILING("ceiling");

        private final String serialized;

        AttachFace(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum Axis {
        X("x"),

        Y("y"),

        Z("z");

        private final String serialized;

        Axis(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum BambooLeaves {
        NONE("none"),

        SMALL("small"),

        LARGE("large");

        private final String serialized;

        BambooLeaves(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum BedPart {
        HEAD("head"),

        FOOT("foot");

        private final String serialized;

        BedPart(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum BellAttachType {
        FLOOR("floor"),

        CEILING("ceiling"),

        SINGLE_WALL("single_wall"),

        DOUBLE_WALL("double_wall");

        private final String serialized;

        BellAttachType(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum ChestType {
        SINGLE("single"),

        LEFT("left"),

        RIGHT("right");

        private final String serialized;

        ChestType(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum ComparatorMode {
        COMPARE("compare"),

        SUBTRACT("subtract");

        private final String serialized;

        ComparatorMode(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum CreakingHeartState {
        UPROOTED("uprooted"),

        DORMANT("dormant"),

        AWAKE("awake");

        private final String serialized;

        CreakingHeartState(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum Direction {
        NORTH("north"),

        EAST("east"),

        SOUTH("south"),

        WEST("west"),

        UP("up"),

        DOWN("down");

        private final String serialized;

        Direction(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum DoorHingeSide {
        LEFT("left"),

        RIGHT("right");

        private final String serialized;

        DoorHingeSide(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum DoubleBlockHalf {
        UPPER("upper"),

        LOWER("lower");

        private final String serialized;

        DoubleBlockHalf(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum DripstoneThickness {
        TIP_MERGE("tip_merge"),

        TIP("tip"),

        FRUSTUM("frustum"),

        MIDDLE("middle"),

        BASE("base");

        private final String serialized;

        DripstoneThickness(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum FrontAndTop {
        DOWN_EAST("down_east"),

        DOWN_NORTH("down_north"),

        DOWN_SOUTH("down_south"),

        DOWN_WEST("down_west"),

        UP_EAST("up_east"),

        UP_NORTH("up_north"),

        UP_SOUTH("up_south"),

        UP_WEST("up_west"),

        WEST_UP("west_up"),

        EAST_UP("east_up"),

        NORTH_UP("north_up"),

        SOUTH_UP("south_up");

        private final String serialized;

        FrontAndTop(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum Half {
        TOP("top"),

        BOTTOM("bottom");

        private final String serialized;

        Half(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum NoteBlockInstrument {
        HARP("harp"),

        BASEDRUM("basedrum"),

        SNARE("snare"),

        HAT("hat"),

        BASS("bass"),

        FLUTE("flute"),

        BELL("bell"),

        GUITAR("guitar"),

        CHIME("chime"),

        XYLOPHONE("xylophone"),

        IRON_XYLOPHONE("iron_xylophone"),

        COW_BELL("cow_bell"),

        DIDGERIDOO("didgeridoo"),

        BIT("bit"),

        BANJO("banjo"),

        PLING("pling"),

        ZOMBIE("zombie"),

        SKELETON("skeleton"),

        CREEPER("creeper"),

        DRAGON("dragon"),

        WITHER_SKELETON("wither_skeleton"),

        PIGLIN("piglin"),

        CUSTOM_HEAD("custom_head");

        private final String serialized;

        NoteBlockInstrument(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum PistonType {
        DEFAULT("normal"),

        STICKY("sticky");

        private final String serialized;

        PistonType(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum Pose {
        STANDING("standing"),

        SITTING("sitting"),

        RUNNING("running"),

        STAR("star");

        private final String serialized;

        Pose(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum RailShape {
        NORTH_SOUTH("north_south"),

        EAST_WEST("east_west"),

        ASCENDING_EAST("ascending_east"),

        ASCENDING_WEST("ascending_west"),

        ASCENDING_NORTH("ascending_north"),

        ASCENDING_SOUTH("ascending_south"),

        SOUTH_EAST("south_east"),

        SOUTH_WEST("south_west"),

        NORTH_WEST("north_west"),

        NORTH_EAST("north_east");

        private final String serialized;

        RailShape(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum RedstoneSide {
        UP("up"),

        SIDE("side"),

        NONE("none");

        private final String serialized;

        RedstoneSide(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum SculkSensorPhase {
        INACTIVE("inactive"),

        ACTIVE("active"),

        COOLDOWN("cooldown");

        private final String serialized;

        SculkSensorPhase(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum SideChainPart {
        UNCONNECTED("unconnected"),

        RIGHT("right"),

        CENTER("center"),

        LEFT("left");

        private final String serialized;

        SideChainPart(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum SlabType {
        TOP("top"),

        BOTTOM("bottom"),

        DOUBLE("double");

        private final String serialized;

        SlabType(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum StairsShape {
        STRAIGHT("straight"),

        INNER_LEFT("inner_left"),

        INNER_RIGHT("inner_right"),

        OUTER_LEFT("outer_left"),

        OUTER_RIGHT("outer_right");

        private final String serialized;

        StairsShape(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum StructureMode {
        SAVE("save"),

        LOAD("load"),

        CORNER("corner"),

        DATA("data");

        private final String serialized;

        StructureMode(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum TestBlockMode {
        START("start"),

        LOG("log"),

        FAIL("fail"),

        ACCEPT("accept");

        private final String serialized;

        TestBlockMode(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum Tilt {
        NONE("none"),

        UNSTABLE("unstable"),

        PARTIAL("partial"),

        FULL("full");

        private final String serialized;

        Tilt(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum TrialSpawnerState {
        INACTIVE("inactive"),

        WAITING_FOR_PLAYERS("waiting_for_players"),

        ACTIVE("active"),

        WAITING_FOR_REWARD_EJECTION("waiting_for_reward_ejection"),

        EJECTING_REWARD("ejecting_reward"),

        COOLDOWN("cooldown");

        private final String serialized;

        TrialSpawnerState(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum VaultState {
        INACTIVE("inactive"),

        ACTIVE("active"),

        UNLOCKING("unlocking"),

        EJECTING("ejecting");

        private final String serialized;

        VaultState(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }

    enum WallSide {
        NONE("none"),

        LOW("low"),

        TALL("tall");

        private final String serialized;

        WallSide(String serialized) {
            this.serialized = serialized;
        }

        public String serialized() {
            return this.serialized;
        }
    }
}
